### ISSUE TITLE
Абстрагироваться от стейта

### ISSUE THREAD

**Issue by NikitaRzm** [stanislav-az/echo-bot#12]
https://github.com/stanislav-az/echo-bot/blob/master/src/Bot/BotClass.hs#L69

Абстрагируйся от того факта, что используешь стейт для этого функционала, спроектируй апиху для сторейджа данных, которые надо хранить, как-будто это абстрактный сторедж типа MonadBotStorage, и соответственно подрефактори функции там :) В идеале чтоб вдруг при желании при написании нового кода для других стореджей можно было и файл использовать, и базу и так далее)

**Comment by stanislav-az** [comment]
Тогда в MonadBotStorage должны быть функции как в MonadState? Сделать put, get, и modify? А в MonadRepeatMapState можно тогда оставить только lookupRepeatDefault и insertRepeat, такая задумка?)

**Comment by NikitaRzm** [comment]
Лучше более заточенно под твои нужды:
getRepeatCount
getLastUpdateId

ну и так далее, т.е. семантические действия, не действия над структурой данных)

**Comment by NikitaRzm** [comment]
Можно еще просто реализовать стандартные операции для стореджа:
retrieve
insert
update

Но у разных бекендов примитивные операции могут быт ьразными, так что это менее удобно и связывает руки в реализации)

**Comment by stanislav-az** [comment]
Вообще, это же у меня и так абстрактный сторедж? Я как раз для этого эти монады делал, чтобы не было констрейнта на MonadState env, иначе потом env должен быть везде одного типа, и нельзя будет нужный env в MockMonad сделать. 
Причем, есть монады общие для обоих ботов:
```
class (Monad m) =>
      MonadLastMsgState m msg
  where
  getLastMsg :: m (Maybe msg)
  putLastMsg :: Maybe msg -> m ()

class (Monad m) =>
      MonadRepeatMapState m
  where
  getRepeatMap :: m (HM.HashMap T.Text Int)
  putRepeatMap :: HM.HashMap T.Text Int -> m ()
  modifyRepeatMap :: (HM.HashMap T.Text Int -> HM.HashMap T.Text Int) -> m ()
  modifyRepeatMap f = getRepeatMap >>= (putRepeatMap . f)
  lookupRepeatDefault :: Int -> T.Text -> m Int
  lookupRepeatDefault v k = HM.lookupDefault v k <$> getRepeatMap
  insertRepeat :: T.Text -> Int -> m ()
  insertRepeat k v = modifyRepeatMap $ HM.insert k v
```
А есть еще для слака только:
```
class (Monad m) =>
      MonadTimestampState m
  where
  getTimestamp :: m (Maybe String)
  putTimestamp :: Maybe String -> m ()
```

**Comment by NikitaRzm** [comment]
У тебя не должно быть конкретного типа в идеале  HasMap, Map, попробуй уйти от него )

**Comment by NikitaRzm** [comment]
Ну если это монадридер ты пилишь, то должен быть тайпкласс типа HasBotStorage, и туда запихать все нужные функции )

**Comment by stanislav-az** [comment]
Попробовал уйти от HashMap, пришлось добавить переменную типа в EchoBot https://github.com/stanislav-az/echo-bot/blob/c264f8c93afe731eca449c1ea6bb89edf51e48a8/src/Bot/EchoBot.hs#L21. Просто с Сергеем как раз недавно убирали специально все переменные оттуда кроме m и msg :) А без добавления переменной не компилится. 
Насчет специализированных функций в HasBotStorage, у меня была ишью, где надо было переделать наоборот, сократить специализированные функции и оставить одну общую)) https://github.com/stanislav-az/echo-bot/issues/2

**Comment by NikitaRzm** [comment]
Ну это не плохо конкретно тут, конкретно там - это было крайне оправданно )

Согласись, что от типа сторейджа надо точно уйти и делать полиморфным: это либо тайпфемели на тайпклассе, либо как ты сделал - но это точно нужно сделать )

Есть те места - где оправданны те или иные вещи, а есть те - где не особо и нужны разные подходы для разных ситуаций, потому не совсем понимаю аналогий ))
