### ISSUE TITLE
А зачем столько методов в тайпклассах Has... ? :)

### ISSUE THREAD

**Issue by Znack** [stanislav-az/echo-bot#2]
Сейчас тайпклассы HasTelegramEnv и HasSlackEnv имеют по куче методов каждый, хотя можно было просто по одному методу сделать getTelegramEnv и getSlackEnv соотвественно и все :) А остальыне функции можно выводить, например. Как в примере статьи про ReaderT тайклассы HasLog и HasBalance имеют самые примитивные методы :)

**Comment by stanislav-az** [comment]
Это ведь касается только HasTelegramEnv и HasSlackEnv, для HasTelegramMod и HasSlackMod лучше не делать подобные преобразования?

**Comment by Znack** [comment]
А я вообще кстати не уверен, что эти тайпклассы нужны :) А зачем они тебе?  Почему просто не доставать это все из TelegramEnv после вызова getTelegramEnv соотвестветнно? :)

**Comment by stanislav-az** [comment]
В них как раз часть окружения, которую нужно изменять ещё, кроме того чтобы доставать просто.

**Comment by Znack** [comment]
ReaderT для этого предлагал MVar юзать :) Тут в принципе сложно сказать, что лучше. А почему ты назвал Mod? Потому что modify можешь вызывать? :)

**Comment by stanislav-az** [comment]
Ага, назвал потому что могу вызывать modify) В ReaderT design pattern там же все равно тайпкласс потом создавали, в котором были функции для модификации. Я просто немного изменил эту схему, чтобы get-функции были вместе с modify-функциями, и добавил put-функции, чтобы можно было потом не писать get и modify, а писать get и put, а modify выражается через get и put.

**Comment by Znack** [comment]
Ага, но ты учти, что там это был тайпкласс для конкретного эффекта, а не просто HasBalanceMod, тебе тогда лучше mtl-like тайпкласс сделать для конкретного эффекта который ты хочешь, например, MonadBotState (и лучше его один сделать на оба бота)
