### ISSUE TITLE
Для EchoBot, мне кажется, лучше объединить тип и для msg, и для react.

### ISSUE THREAD

**Issue by Znack** [stanislav-az/echo-bot#5]
У тебя же только в слаке есть эта особенность. Там проще сделать тогда только для слака ADT по типу 
```
data SlackMessage = PlainMessage T.Text | Reaction T.Text
```
Надо из типа EchoBot все по максимуму выпилиывать, а то сейчас он оооочень монструозный получился :) И оставлять все по-максимуму обобщенное, чтобы в дальнейшем новый вид мессенджера было легко подключить

**Comment by stanislav-az** [comment]
Как раз эта особенность (ADT -Reaction) появилась сначала для телеграма. Знаю, тип выглядит не очень приятно, это я ещё его сократил) В телеграме не обойтись без 
```
data TelegramReaction = TelegramReaction
  { trUpdateId :: Integer
  , trId :: String
  , trChatId :: Integer
  , trCallbackData :: String
  } deriving (Eq, Show)
```
Так как нужно отправлять еще ответ на нажатие кнопки с клавиатуры, по id от [CallbackQuery](https://core.telegram.org/bots/api#callbackquery).

**Comment by Znack** [comment]
Ну тогда для TelegramMessage тоже сделай сумму типов :)
