### ISSUE TITLE
Отрефакторить все, что связано с итератором

### ISSUE THREAD

**Issue by Znack** [stanislav-az/echo-bot#6]
Тяжело разобраться с тем, что такое параметр `iter` у EchoBot, что такое `iteratorTransformation` и как им пользоваться, типы и примеры испольщования не особо помогли, даже когда в реализацию `sIteratorTransformation ` для слака залез, не очень помогло :)

Можешь тут вкратце объяснить скрытый смысл за этой темой, я думаю, что мы можем вместе гораздо более понятную и очевидную абстракцию придумать :)

**Comment by stanislav-az** [comment]
Необходимо запоминать определенное значение "итератора" для того чтобы не получать лишние обновления на каждой итерации `botCycle`.
Для телеграма это id последнего [обновления](https://core.telegram.org/bots/api#update), используется при отпраке [запроса](https://core.telegram.org/bots/api#getupdates) на получение обновлений в параметре offset.
Для слака это timestamp (`"ts": "1503435956.000247"`) последнего обработанного сообщения, используется при отправке [запроса](https://api.slack.com/methods/conversations.history) на получение истории сообщений в параметре oldest.

**Comment by Znack** [comment]
А имея на руках последнее сообщение, ты же можешь в каждом случае понимать, как отправлять запрос? Может из EchoBot убрать iter, а в функцию getUpdates передавать `Maybe mes`, таким образом, ты еще и iteratorTransformation уберёшь? :)
